
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-metrics-sender
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: iothub-metrics-sender
    spec:
      containers:
      - name: iothub-metrics-sender
        image: toszo/iothub-metrics-sender:0.1.0
        imagePullPolicy: Always
        env:
        - name: WAIT_TIME
          value: "3000"
        - name: IOTHUB_DEVICE_CONN_STRING
          value: ""
        - name: EXPORTER_URL
          value: "http://10.0.4.8:9100/metrics"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
