---

- name: Check if self signed certificate exists on node
  stat:
    path: /tmp/{{ self_signed_certificate_name }}
  register: certificate_node

- name: Check if private key for self signed certificate exists on node
  stat:
    path: /tmp/{{ self_signed_private_key_name }}
  register: privkey_node

- name: Generate private key if certificate hasn't been found in directory
  shell: openssl req -x509 -nodes -newkey rsa:4096 -keyout /tmp/{{ self_signed_private_key_name }} -out /tmp/{{ self_signed_certificate_name }} -days 365 -subj '/CN=localhost' 
  when: 
    - not certificate_node.stat.exists
    - not privkey_node.stat.exists

- name: Check if certificate exists on node
  stat:
    path: /tmp/{{ self_signed_certificate_name }}
  register: certificate_node

- name: Check if certificate exists on node
  stat:
    path: /tmp/{{ self_signed_private_key_name }}
  register: privkey_node

- name: Check if  certificate exists on node
  stat: 
    path: /tmp/{{ self_signed_concatenated_cert_name }}
  register: cert_consolidated

- name: Display if cert exists
  debug: 
    msg: "Cert doesn't exist"
  when:
    - not cert_consolidated.stat.exists

- name: Concatenate key and cert for haproxy
  shell: cat /tmp/{{ self_signed_certificate_name }} /tmp/{{ self_signed_private_key_name }} > /tmp/{{ self_signed_concatenated_cert_name }}
  when: 
    - certificate_node.stat.exists
    - privkey_node.stat.exists
    - not cert_consolidated.stat.exists
