---
- name: Add Docker-CE stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

# Workaround for problems with container selinux. 
# Todo: Investigate problems with container selinux on Azure.
- name: Install container packages
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm
    state: present
    update_cache: yes

- name: Install Docker
  yum:
    name: docker-ce-18.06.3.ce-3.el7
    state: present
    update_cache: yes
