---
# Ansible playbook that makes sure the base items for all nodes are installed

- hosts: all
  tasks: [ ]  

- hosts: haproxy_tls_termination
  become: true
  become_method: sudo
  roles:
    - haproxy_tls_termination
