---
# Kafka verification test

- hosts: kafka[0]
  become: true
  become_method: sudo
  tasks:
    - name: Kafka topic create verification
      shell: /opt/kafka/bin/kafka-topics.sh --create --topic epiphanyverify --partitions 1 --replication-factor 1 --zookeeper localhost:2181
      become_user: operations

    - name: Kafka topic list verification
      shell: /opt/kafka/bin/kafka-topics.sh --list --topic epiphanyverify --zookeeper localhost:2181
      become_user: operations

    - name: Kafka topic delete verification
      shell: /opt/kafka/bin/kafka-topics.sh --delete --topic epiphanyverify --zookeeper localhost:2181
      become_user: operations
