---
# HaProxy Red Hat family of specific tasks

- name: Install haproxy family packages
  yum:
    name: 
      - rh-haproxy18
      - rh-haproxy18-haproxy-syspaths
    update_cache: yes
    state: present

- name: Copy haproxy config
  template: 
    dest: /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg
    src: "haproxy_{{ ansible_os_family }}.cfg.j2"

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted

- name: Enable haproxy service
  service:
    name: haproxy
    enabled: yes

- name: Stop services
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable SELinux at next reboot
  selinux:
    state: disabled
  ignore_errors: yes

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

- name: Uncomment modules loading
  replace:
    path: /etc/rsyslog.conf
    regexp: '#$ModLoad imudp'
    replace: '$ModLoad imudp'

- name: Uncomment modules loading
  replace:
    path: /etc/rsyslog.conf
    regexp: '#$UDPServerRun 514'
    replace: '$UDPServerRun 514'

- name: Copy haproxy rsyslog config
  copy:
    dest: /etc/rsyslog.d/haproxy.conf
    src: "haproxy_rsyslog_{{ ansible_os_family }}.conf"

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
