
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iothub-metrics-collector
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: iothub-metrics-collector
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
         claimName: task-pv-claim
      containers:
      - name: iothub-metrics-collector
        image: toszo/iothub-metrics-collector:0.1.0
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/shared"
            name: task-pv-storage
        env:

        - name: PATH_TO_STORE
          value: "/shared"
        - name: WAIT_TIME
          value: "5"
        - name: EVENT_HUB_COMPATIBLE_ENDPOINT
          value: ""
        - name: EVENT_HUB_COMPATIBLE_PATH
          value: ""
        - name: IOT_HUB_SAS_KEY_NAME
          value: ""
        - name: IOT_HUB_SAS_KEY
          value: ""

        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      nodeSelector:
        iotmetrics: true
