---
indices_retention_days: 30
debian_curator_version: "5.5.4_amd64"
redhat_curator_version: "5.5.4-1.x86_64"

elasticsearch_ip: "{{ hostvars[groups['elasticsearch'][0]]['ansible_default_ipv4']['address'] }}"

elasticsearch_curator_cron_jobs:
  - {
      name: "Delete old elasticsearch indices.",
      job: "curator_cli --host '{{ elasticsearch_ip }}' delete_indices --filter_list '[{\"filtertype\":\"age\",\"source\":\"creation_date\",\"direction\":\"older\",\"unit\":\"days\",\"unit_count\":{{ indices_retention_days }}}]'",
      minute: 0,
      hour: 1
  }