---

- name: Create directory
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: Create tmp directory
  file:
    path: "{{ backup_dir }}/tmp"
    state: directory

- name: Unarchive a zip archive
  unarchive:
    src: "{{ backup_dir }}/k8s_backup.zip"
    dest: "{{ backup_dir }}/tmp"
    remote_src: yes

- name: Restore certificates
  copy:
    src: "{{ backup_dir }}/tmp/pki/"
    dest: /etc/kubernetes/pki
    remote_src: yes
  register: output

- debug:
    var: output

- name: Create directory
  file:
    path: /var/lib/etcd
    state: directory

- name: Get etcd image name
  shell: docker images | awk '/etcd/ {print $1":"$2}' | awk 'NR==1'
  register: etcd_image_name

- debug:
    var: etcd_image_name

- name: Restore etcd backup
  shell: >
    docker run -v "{{ backup_dir }}/tmp":/backup  \
    -v /var/lib/etcd:/var/lib/etcd \
    --env ETCDCTL_API=3 \
    --rm {{ etcd_image_name.stdout }} \
    /bin/sh -c "etcdctl snapshot restore '/backup/etcd-snapshot.db'; cp -r /default.etcd/member/ /var/lib/etcd/"
  register: output

- debug:
    var: output

- name: Initialize the master with backup
  shell: kubeadm init --ignore-preflight-errors=DirAvailable--var-lib-etcd 
  register: output

- debug:
    var: output
  
- name: Clean tmp directory
  file:
    state: absent
    path: "{{ backup_dir }}/tmp/"


