---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: setup-ssl.yml

- include_tasks: reverse-proxies.yml

- name: Ensure nginx is started and enabled to start at boot.
  systemd: name=nginx state=started enabled=yes
