---
- name: Install role dependencies
  yum:
    name: 'python-passlib'
    state: 'present'
  when: nginx_basic_auth

- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure nginx is installed.
  yum:
    name: nginx
    state: present

- name: Create default nginx directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '/usr/share/nginx/html'
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
    - '/etc/nginx/conf.d'
    - '/etc/nginx/ssl'

- name: Remove default site
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '/var/www/html'
    - '/etc/nginx/sites-enabled/default'
    - '/etc/nginx/sites-available/default'
  notify:
    - Test nginx and reload

- name: Configure nginx
  template:
    src: 'etc/nginx/nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  register: nginx_register_nginx_config
  notify:
    - Test nginx and reload

