
- name: Configure reverse-proxies
  template:
    src: 'etc/nginx/sites-available/reverse-proxy.conf.j2'
    dest: '/etc/nginx/sites-available/{{ item.config_name }}.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  with_items: '{{ reverse_proxies }}'
  notify:
    - Test nginx and reload

- name: Symlink sites-available to sites-enabled - reverse proxies
  file:
    src: '/etc/nginx/sites-available/{{ item.config_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.config_name }}.conf'
    state: 'link'
  with_items: '{{ reverse_proxies }}'
  notify:
    - Test nginx and restart