---
- name: Wait until the cluster is available
  shell: kubectl --kubeconfig=/home/{{ admin_user.name }}/.kube/config cluster-info
  retries: 10
  delay: 5
  register: output
  until: output is succeeded
  
- name: Include deployments
  include_tasks: "applications/{{ item.name }}/main.yml"
  vars:
    data: "{{ item }}"
  loop: "{{ kubernetes.deployments }}"
  when:
    - kubernetes.deployments is defined and kubernetes.deployments | length > 0
