---
url: "https://github.com/danielqsj/kafka_exporter/releases/download/v{{ kafka_exporter_version }}/{{ kafka_exporter_release_name }}.tar.gz"

go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'
